epochs: [100]
min_lr: [0]
virtual_node: [0]
lr_schedule_patience: [101]
JK: ["concat"]

cat: [1]
spiderweb: [0]
lr_scheduler: ["None"]

model: ["GIN"]
batch_size: [128]
emb_dim: [64]
drop_out: [0]
num_layer: [4]
pooling: ["mean"]
lr:  [0.001]
num_mlp_layers: [2]
